"""empty message

Revision ID: 0186c27a9da1
Revises: 4775112577a7
Create Date: 2023-01-27 21:54:47.020764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0186c27a9da1'
down_revision = '4775112577a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupant_first_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('occupant_last_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('occupant', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('occupant_phone_num', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('occupant_address', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_data', schema=None) as batch_op:
        batch_op.drop_column('occupant_address')
        batch_op.drop_column('occupant_phone_num')
        batch_op.drop_column('occupant')
        batch_op.drop_column('occupant_last_name')
        batch_op.drop_column('occupant_first_name')

    # ### end Alembic commands ###
