"""site added

Revision ID: 11f51c5ef4cc
Revises: a37a4f153b30
Create Date: 2023-01-06 17:28:02.941825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f51c5ef4cc'
down_revision = 'a37a4f153b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_time_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_time_test', schema=None) as batch_op:
        batch_op.drop_column('site')

    # ### end Alembic commands ###
