"""migrate

Revision ID: 2bc885e79fcc
Revises: 
Create Date: 2022-12-02 16:15:17.419332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc885e79fcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campground', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('inner_campground', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('inner_campground')
        batch_op.drop_column('campground')

    # ### end Alembic commands ###
