"""forms

Revision ID: 2f781b78a97d
Revises: c2f770cfbb5c
Create Date: 2022-12-08 19:03:40.591631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f781b78a97d'
down_revision = 'c2f770cfbb5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_num', sa.String(length=11), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_num', sa.String(length=11), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_num')

    with op.batch_alter_table('booking_data', schema=None) as batch_op:
        batch_op.drop_column('contact_num')

    # ### end Alembic commands ###
