"""empty message

Revision ID: 531a44fde528
Revises: 0186c27a9da1
Create Date: 2023-01-27 22:07:37.095711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531a44fde528'
down_revision = '0186c27a9da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupant_postal_codee', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_data', schema=None) as batch_op:
        batch_op.drop_column('occupant_postal_codee')

    # ### end Alembic commands ###
