"""campupdate

Revision ID: c2f770cfbb5c
Revises: 2bc885e79fcc
Create Date: 2022-12-08 18:47:50.473704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f770cfbb5c'
down_revision = '2bc885e79fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campground', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('inner_campground', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_data', schema=None) as batch_op:
        batch_op.drop_column('inner_campground')
        batch_op.drop_column('campground')

    # ### end Alembic commands ###
